name: Node.js CI on Ubuntu

on:
  push:
    branches: [ heroku-test ]
  pull_request:
    branches: [ heroku-test ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{  matrix.node-version }}
    - run: |
        npm i
        npm run build
        pm2 stop webapp
        pm2 start /home/runner/webapp/actions-runner/_work/journal-web-app/journal-web-app/server.js --name=webapp
        pm2 save
